AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless backend for the Bill Printing app. Provides REST APIs backed by
  Lambda and DynamoDB.

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
    Handler: src/index.handler
    CodeUri: .
    Environment:
      Variables:
        TABLE_NAME: !Ref BillingTable
        STAGE_NAME: !Ref ApiStageName
        BILL_TTL_DAYS: !Ref BillTtlDays
        ADMIN_PASSCODE: !Ref AdminPasscode

Parameters:
  ApiStageName:
    Type: String
    Default: prod
    Description: API Gateway stage for deployment (e.g. dev, prod)

  BillingTableName:
    Type: String
    Default: BillingAppTable
    Description: DynamoDB table name

  BillTtlDays:
    Type: Number
    Default: 30
    Description: Number of days to retain bills/items before automatic expiry

  AdminPasscode:
    Type: String
    Default: '7022537312'
    Description: Passcode required for login authentication
    NoEcho: true

Resources:
  BillingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        MaxAge: "'600'"
      EndpointConfiguration: REGIONAL

  BillingServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handles all REST endpoints for billing workflows
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BillingTable
      Events:
        AuthLogin:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
            RestApiId: !Ref BillingApi
        AuthLogout:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: post
            RestApiId: !Ref BillingApi
        AuthVerify:
          Type: Api
          Properties:
            Path: /auth/verify
            Method: get
            RestApiId: !Ref BillingApi
        CustomersList:
          Type: Api
          Properties:
            Path: /customers
            Method: get
            RestApiId: !Ref BillingApi
        CustomersCreate:
          Type: Api
          Properties:
            Path: /customers
            Method: post
            RestApiId: !Ref BillingApi
        CustomerDelete:
          Type: Api
          Properties:
            Path: /customers/{customerId}
            Method: delete
            RestApiId: !Ref BillingApi
        CustomerGet:
          Type: Api
          Properties:
            Path: /customers/{customerId}
            Method: get
            RestApiId: !Ref BillingApi
        CustomerBillsList:
          Type: Api
          Properties:
            Path: /customers/{customerId}/bills
            Method: get
            RestApiId: !Ref BillingApi
        CustomerBillsCreate:
          Type: Api
          Properties:
            Path: /customers/{customerId}/bills
            Method: post
            RestApiId: !Ref BillingApi
        BillGet:
          Type: Api
          Properties:
            Path: /bills/{billId}
            Method: get
            RestApiId: !Ref BillingApi
        BillDelete:
          Type: Api
          Properties:
            Path: /bills/{billId}
            Method: delete
            RestApiId: !Ref BillingApi
        BillUpsert:
          Type: Api
          Properties:
            Path: /bills/{billId}
            Method: put
            RestApiId: !Ref BillingApi
        BillPrint:
          Type: Api
          Properties:
            Path: /bills/{billId}/pdf
            Method: get
            RestApiId: !Ref BillingApi

  BillingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref BillingTableName
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ['*']
            AllowedMethods: ['GET', 'HEAD']
            AllowedHeaders: ['*']
            MaxAge: 3600

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendBucket.Arn}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}'

  # CloudFront Origin Access Control (OAC) - for secure S3 access
  FrontendOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-frontend-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: OAC for secure S3 access via CloudFront

  # CloudFront Distribution
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt FrontendOAC.Id
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        Comment: !Sub 'CloudFront distribution for ${AWS::StackName} frontend'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  ApiUrl:
    Description: Invoke URL for the deployed API Gateway stage
    Value: !Sub 'https://${BillingApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}'
  DynamoTableName:
    Description: DynamoDB table that stores customers, bills and items
    Value: !Ref BillingTable
  FrontendBucketName:
    Description: S3 bucket hosting the React frontend
    Value: !Ref FrontendBucket
  FrontendWebsiteUrl:
    Description: CloudFront distribution URL for the frontend (use this URL to access the app)
    Value: !GetAtt FrontendDistribution.DomainName
  FrontendDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref FrontendDistribution
  FrontendDistributionUrl:
    Description: Full CloudFront URL (https://)
    Value: !Sub 'https://${FrontendDistribution.DomainName}'

